### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by sudo-prime** [surrsurus/YACS#3]
This ticket contains the design work for the main menu look and layout. This requires https://github.com/surrsurus/YACS/issues/1.

**Acceptance Criteria:**
- [x] The user is greeted by the main menu on program startup.
- [x] The main menu should have properly labeled buttons leading to various parts of the app.
- [x] The main menu should display the name of our project.

**Comment by surrsurus** [comment]
Want to close this? looks done to me by the criteria
