### ISSUE TITLE
Piece validation

### ISSUE THREAD

**Issue by sudo-prime** [surrsurus/YACS#8]
When a player attempts to move a piece, they should be able to see all valid spots for that piece. This ticket encapsulates only the basic piece movements.

**Acceptance Criteria:**
- [x] When a user clicks a rook, the available moves should be tiles up / down / left / right of that rook.
- [x] When a user clicks a bishop, the available moves should be tiles diagonal of that rook.
- [x] etc. for all pieces.
- [x] The user CAN'T move two of their pieces on top of each other.
- [x] The user CAN move a piece of theirs on top of an enemy piece.

The AC for this ticket does NOT include:
special cases such as en passant,
castling, queen promotion,
check, checkmate, capture of enemy pieces

**Comment by surrsurus** [comment]
Done as of #27
